version: '3.8'

services:
  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
